name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: IpsApi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish" 
  AZURE_CONTAINER_REGISTRY: AzRegistry


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with: 
            dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        

    
        
